---
version: '3'
services:

  web-mysql:
    image: mysql:latest
    env_file: ./.env
    ports:
      - "3306:3306"

  web-js:
    build:
      dockerfile: Dockerfile.js
      context: .
    env_file: .env
    volumes:
      - ./booking/static/js/vue/:/app/static/js/vue
    command: ["/usr/local/bin/npm", "run", "dev"]

  web:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./booking:/app
    ports:
      - "80:8080"
    command: ./scripts/cmd-web.sh
    environment:
      MYSQL_HOST: web-mysql
    env_file: ./.env
    depends_on:
      - web-mysql
